In [2]:
#Let's test numpy array execution and regular python array. And see which is faster
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [3]:
%timeit my_arr2 = my_arr *2

1.84 ms ± 26.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%timeit my_list2 = [x * 2 for x in my_list]

138 ms ± 40.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
a = np.array([[1.,2.,3.5],
             [2.,6.,1.2],
             [3.,7.,2.4],
             [0.,2.5,1.]])
#create b matrix with 0s in desired dimension you like added in tuple
b = np.zeros((a.shape[0],a.shape[1]-1))

#add a range of values 0,1,2,3,4...n-1 => np.arange(n)
c = np.arange(15)

#convert a list to np.array along with data tye conversion
d = np.array(c, dtype=np.float64)

#explicitly convert data types
conver = d.astype(np.float32)

#if you want to convert the data type from different array
currentCal = c.astype(conver.dtype)

a.dtype, a.shape, a.shape[0], a.ndim, b

(dtype('float64'),
 (4, 3),
 4,
 2,
 array([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]))

In [20]:
#comparisons between arrays
a = np.array([[2,5,1],
             [0,4,2]], dtype=np.int8)
b = np.array([[2,1,6],
             [9,4,1]], dtype=np.int8)

#replace values
aa = a.copy()
aa[:,1:] = 7
a == b, a>b, aa, a, a[1,2]

(array([[ True, False, False],
        [False,  True, False]]),
 array([[False,  True, False],
        [False, False,  True]]),
 array([[2, 7, 7],
        [0, 7, 7]], dtype=int8),
 array([[2, 5, 1],
        [0, 4, 2]], dtype=int8),
 2)

In [40]:
#try to create matrix
q = [[i+j for i in range(3)] for j in range(2)]
q = np.array(q, dtype=np.int8)
q, q[:2, 1]

(array([[0, 1, 2],
        [1, 2, 3]], dtype=int8),
 array([1, 2], dtype=int8))

In [57]:
#boolean indexing and filtering using numpy
#to achieve this, both arrays should be of the same length in axis=0
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])

data[names=="Joe"]
#show all matching but only show from second column
data[names=="Joe", 1:]

#show all matching but only show second column
data[names=="Joe", 1]

#select everythng but "Joe". Both are correct
data[~(names=="Joe")] ,data[names != "Joe"]

#you can make condition by yourself. | mean "or" and & mean "and"
cond = (names=="Joe") | (names=="Bob")
data[cond]

#if you want to assign all negative values to 0
data[data < 0] = 0

#write value explicitly
data[names=="Joe"] = 7

array([[  4,   7],
       [  0,   2],
       [  0,   0],
       [-12,  -4],
       [  3,   4]])

In [77]:
#fancy indexing
a = [[j+i*4 for j in range(4)] for i in range(8)]
a = np.array(a, dtype=np.int8)

#it will print a[2,0] and a[4,2]
a[[2,4],[0,2]]

#assigning values. values in a[2,0] and a[4,2] will be 0
a[[2,4],[0,2]] = 0

#you can reshape and rotate or transpose array
b = np.arange(15).reshape((3,5))
#both are correct for transposing
b.T, b.swapaxes(0,1), b

#you can do matrix multiplication in both ways
np.dot(b.T, b), b.T @ b


(array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]),
 array([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]))

In [82]:
#pseudorandom
rng = np.random.default_rng(seed=12345)

data = rng.standard_normal((2,3))
data = data *5

#you can split in 2 matrix. One with whole number, the other one just reminder
reminder, whole = np.modf(data)
reminder, whole, np.sign(whole)

(array([[-0.11912518,  0.31864229, -0.35330869],
        [-0.29586617, -0.37671654, -0.70442326]]),
 array([[-7.,  6., -4.],
        [-1., -0., -3.]]),
 array([[-1.,  1., -1.],
        [-1.,  0., -1.]]))

In [87]:
#conditional logic expressions
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

#it will be very slow for huge array
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

#the better solution is by using np.where. It is like IIF in SQL
result1 = np.where(cond, xarr, yarr)
result, result1

b = rng.standard_normal((2,3))
res = np.where(b<0, -1, 1)

#you can combine scalar and array
res1 = np.where(b<0, -1, b)
b, res, res1

(array([[ 0.57585751,  1.39897899,  1.32229806],
        [-0.29969852,  0.90291934, -1.62158273]]),
 array([[ 1,  1,  1],
        [-1,  1, -1]]),
 array([[ 0.57585751,  1.39897899,  1.32229806],
        [-1.        ,  0.90291934, -1.        ]]))

In [92]:
#statistical methods
sta = rng.standard_normal((2,3))
#these both are identical
sta.mean(), np.mean(sta)

#you can use axis
mean_r = sta.mean(axis=0)
mean_c = sta.mean(axis=1)
sta, mean_r, mean_c

#cumulutative sum is for financial purpose to sum rows or cols based on axis
cums = sta.cumsum(axis=0)
sta, cums

(array([[0.06114402, 0.0709146 , 0.43365454],
        [0.27748366, 0.53025239, 0.53672097]]),
 array([[0.06114402, 0.0709146 , 0.43365454],
        [0.33862768, 0.60116699, 0.97037551]]))

In [96]:
#methods for boolean arrays
arr = rng.standard_normal(100)
sumTotal = (arr < 0).sum()
sumTotal

#sort values
arr.sort()

#sort based on axis
arr1 = rng.standard_normal((4,5))
arr1.sort(axis=0)
arr1

#this kind of sorting is making copy
arr2 = np.sort(arr1)

array([[-1.8708905 , -1.49848205, -0.08473721, -0.82169797, -2.21108587],
       [ 0.43597419, -1.17264499,  0.20345047, -0.38460681, -0.94237273],
       [ 0.56434513, -0.97475833,  0.70638953,  0.21242713,  0.73004882],
       [ 1.26177194, -0.26705217,  1.445592  ,  0.53486059,  0.90008171]])

In [99]:
#uniqueness
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])

#show only unique names sorted by default
np.unique(names)

#for numbers
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

#in1d will return if set num exists
values = np.array([6, 0, 0, 3, 2, 5, 6])

np.in1d(values, [2, 3, 6])

array([ True, False, False,  True,  True, False,  True])

In [109]:
#File input and output
arr = np.arange(10)
np.save("numpyfiles/some_array", arr)

#you can save in dictionary format
keys = np.array(["saz", "bez", "cex"])
vals = np.array([1,2,3])
#error with encoding
np.savez("numpyfiles/sampledict.txt", a=keys, b=vals)

np.savetxt("numpyfiles/sampledata.csv", vals, delimiter=',')

#load data
a= np.load("numpyfiles/sampledata.csv")
a

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [121]:
#inverse matrix
a = np.array([[1,6,3],[5,2,9],[4,2,1]])
b = np.linalg.inv(a)
x

array([[ 1.00000000e+00,  0.00000000e+00, -3.33066907e-16],
       [-5.55111512e-17,  1.00000000e+00, -8.32667268e-17],
       [ 1.11022302e-16,  5.55111512e-17,  1.00000000e+00]])